FROM python:3.11-slim

WORKDIR /app
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./
RUN uv sync

COPY scrape_chrono_start.py .

CMD ["uv", "run", "python", "scrape_chrono_start.py"]